### ISSUE TITLE
Command via DeluxeMenu or Console broken

### ISSUE THREAD

**Issue by BiGUNMAN** [BentoBoxWorld/Biomes#24]
#### Description
When executing a biome change command via console or DeluxeMenu (console function), the command returns an error and does not change anything.

Image of error: https://i.imgur.com/7yVblAT.png

####  Steps to reproduce the behavior:
1. Go to your console and change someone's biome using 'bsb biomes set {USER} SNOWY_TUNDRA ISLAND`.
2. This exact command worked for me in-game, but returned those errors in console.

#### Expected behavior
The biome should change and no errors should be posted. The user that had his biome changed should receive a message saying their biome was changed.

#### Screenshots or video
https://i.imgur.com/7yVblAT.png

#### Server Information:
 - Database being used: YAML
 - OS: Ubuntu
 - Java Version: 8
 - BentoBox version: 1.4
 - Addons installed? https://i.imgur.com/Lyu1zmy.png

**Comment by tastybento** [comment]
Should be fixed with last commit.

**Comment by BiGUNMAN** [comment]
@tastybento Would you mind compiling the new version for a .jar download? :)

**Comment by tastybento** [comment]
@BiGUNMAN You can find it on the CI server here: https://ci.codemc.org/job/BentoBoxWorld/job/Biomes/

**Comment by BiGUNMAN** [comment]
@tastybento So it looks like an error is still being thrown, but it does successfully change the biome now: https://i.imgur.com/ZkN1bRS.png

**Comment by tastybento** [comment]
@BiGUNMAN Thanks for the report. It was due to a logging bug that was assuming the calling entity was a player, but in this case it is console. Should be fixed now. Please test.

**Comment by variananora** [comment]
It's still broken and it didn't change the biome.
https://pastebin.com/XgjUn1NC

**Comment by BONNe** [comment]
Implement in 1.5.0.0 version.
