### ISSUE TITLE
Biome Change Cooldown not working?

### ISSUE THREAD

**Issue by Waterman1001** [BentoBoxWorld/Biomes#45]
#### Description

The Biome Change Cooldown is not working for me.
I am using a Cooldown of 86400 seconds. (24 hours).

####  Steps to reproduce the behavior:
1. Go to 'bsbadmin biomes'
2. Click on 'settings'
3. Set cooldown to 86400
4. Try to change a biome as a user without OP
5. Try it again, it still works, no cooldown is applied.

#### Expected behavior
I expected I had to wait till I could use it again.

#### Server Information:
 - Java Version: Java 8.
 - BentoBox version:
31.08 03:05:16 [Server] Server thread/INFO Running SPIGOT 1.14.4.
31.08 03:05:16 [Server] Server thread/INFO BentoBox version: 1.7.0-SNAPSHOT-b1337
31.08 03:05:16 [Server] Server thread/INFO Database: JSON
31.08 03:05:16 [Server] Server thread/INFO Loaded Game Worlds:
31.08 03:05:16 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Overworld, Nether, End
31.08 03:05:16 [Server] Server thread/INFO Loaded Addons:
31.08 03:05:16 [Server] Server thread/INFO Biomes 1.6.0.2-SNAPSHOT-b135 (ENABLED)
31.08 03:05:16 [Server] Server thread/INFO BSkyBlock 1.6.0 (ENABLED)
31.08 03:05:16 [Server] Server thread/INFO Challenges 0.8.0-SNAPSHOT-#324 (ENABLED)

####  Additional context

Help :D

**Comment by BONNe** [comment]
Fixed in latest snapshot.

**Comment by Waterman1001** [comment]
I tried the latest snapshot, but for some reason the Cooldown is still not being applied
I can swap Biomes as fast as I want...
